SET HEADING ON
SET FEEDBACK OFF
SELECT COUNT(*) AS USUARIOS FROM USUARIOS;
SELECT COUNT(*) AS EXPEDIENTES FROM EXPEDIENTES;
SELECT COUNT(*) AS ACTUACIONES FROM ACTUACIONES;
SELECT COUNT(*) AS DOCUMENTOS FROM DOCUMENTOS;
SELECT COUNT(*) AS EVENTOS_HISTORICO FROM EVENTOS_HISTORICO;
SELECT COUNT(*) AS NOTIFICACIONES FROM NOTIFICACIONES;
EXIT;
