-- Oracle schema for DBeaver with safe drop + create
-- Execute this script in DBeaver against the target schema.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NOTIFICACIONES CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EVENTOS_HISTORICO CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DOCUMENTOS CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACTUACIONES CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EXPEDIENTES CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NOTIFICACIONES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EVENTOS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DOCUMENTOS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ACTUACIONES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EXPEDIENTES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIOS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE SEQ_EXPEDIENTES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOCUMENTOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ACTUACIONES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENTOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTIFICACIONES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USUARIOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE USUARIOS (
    id NUMBER(19) NOT NULL,
    uid VARCHAR2(100) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    rol VARCHAR2(50),
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

CREATE INDEX idx_usuarios_uid ON USUARIOS(uid);
CREATE INDEX idx_usuarios_email ON USUARIOS(email);

CREATE TABLE EXPEDIENTES (
    id NUMBER(19) NOT NULL,
    numero_expediente VARCHAR2(50) NOT NULL UNIQUE,
    asunto VARCHAR2(100) NOT NULL,
    tipo VARCHAR2(100),
    estado VARCHAR2(50) NOT NULL,
    procedimiento VARCHAR2(100),
    descripcion VARCHAR2(1000),
    interesado_id NUMBER,
    asignado_a_id NUMBER,
    version NUMBER(19) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_exp_interesado FOREIGN KEY (interesado_id) REFERENCES USUARIOS(id),
    CONSTRAINT fk_exp_asignado FOREIGN KEY (asignado_a_id) REFERENCES USUARIOS(id),
    CONSTRAINT pk_expedientes PRIMARY KEY (id)
);

CREATE INDEX idx_exp_numero ON EXPEDIENTES(numero_expediente);
CREATE INDEX idx_exp_estado ON EXPEDIENTES(estado);
CREATE INDEX idx_exp_fecha_creacion ON EXPEDIENTES(fecha_creacion DESC);
CREATE INDEX idx_exp_interesado ON EXPEDIENTES(interesado_id);
CREATE INDEX idx_exp_asignado ON EXPEDIENTES(asignado_a_id);

CREATE TABLE ACTUACIONES (
    id NUMBER(19) NOT NULL,
    expediente_id NUMBER NOT NULL,
    tipo VARCHAR2(100),
    estado VARCHAR2(50) NOT NULL,
    asignado_a_id NUMBER,
    fecha_inicio TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_fin TIMESTAMP,
    CONSTRAINT fk_act_expediente FOREIGN KEY (expediente_id) REFERENCES EXPEDIENTES(id),
    CONSTRAINT fk_act_asignado FOREIGN KEY (asignado_a_id) REFERENCES USUARIOS(id),
    CONSTRAINT pk_actuaciones PRIMARY KEY (id)
);

CREATE INDEX idx_act_expediente ON ACTUACIONES(expediente_id);
CREATE INDEX idx_act_asignado ON ACTUACIONES(asignado_a_id);

CREATE TABLE DOCUMENTOS (
    id NUMBER(19) NOT NULL,
    expediente_id NUMBER NOT NULL,
    actuacion_id NUMBER,
    tipo VARCHAR2(100),
    version_doc NUMBER(10) NOT NULL,
    estado VARCHAR2(50) NOT NULL,
    ruta_archivo VARCHAR2(500) NOT NULL,
    tamanio_bytes NUMBER,
    id_portafirmas VARCHAR2(255),
    certificado_firmante VARCHAR2(500),
    fecha_firma TIMESTAMP,
    razon_rechazo VARCHAR2(500),
    version NUMBER(19) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_doc_expediente FOREIGN KEY (expediente_id) REFERENCES EXPEDIENTES(id),
    CONSTRAINT fk_doc_actuacion FOREIGN KEY (actuacion_id) REFERENCES ACTUACIONES(id),
    CONSTRAINT uq_id_portafirmas UNIQUE (id_portafirmas),
    CONSTRAINT pk_documentos PRIMARY KEY (id)
);

CREATE INDEX idx_doc_expediente ON DOCUMENTOS(expediente_id);
CREATE INDEX idx_doc_actuacion ON DOCUMENTOS(actuacion_id);
CREATE INDEX idx_doc_estado ON DOCUMENTOS(estado);

CREATE TABLE EVENTOS_HISTORICO (
    id NUMBER(19) NOT NULL,
    expediente_id NUMBER NOT NULL,
    tipo_evento VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(500) NOT NULL,
    usuario_id NUMBER,
    timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ip_address VARCHAR2(50),
    user_agent VARCHAR2(500),
    CONSTRAINT fk_evt_expediente FOREIGN KEY (expediente_id) REFERENCES EXPEDIENTES(id),
    CONSTRAINT fk_evt_usuario FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id),
    CONSTRAINT pk_eventos_historico PRIMARY KEY (id)
);

CREATE INDEX idx_evt_expediente ON EVENTOS_HISTORICO(expediente_id);
CREATE INDEX idx_evt_timestamp ON EVENTOS_HISTORICO(timestamp DESC);
CREATE INDEX idx_evt_usuario ON EVENTOS_HISTORICO(usuario_id);

CREATE TABLE NOTIFICACIONES (
    id NUMBER(19) NOT NULL,
    expediente_id NUMBER NOT NULL,
    documento_id NUMBER,
    email_destinatario VARCHAR2(255) NOT NULL,
    estado VARCHAR2(50) NOT NULL,
    intentos_realizados NUMBER(10) DEFAULT 0 NOT NULL,
    proximo_reintento TIMESTAMP,
    mensaje_error VARCHAR2(500),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_envio TIMESTAMP,
    CONSTRAINT fk_notif_expediente FOREIGN KEY (expediente_id) REFERENCES EXPEDIENTES(id),
    CONSTRAINT fk_notif_documento FOREIGN KEY (documento_id) REFERENCES DOCUMENTOS(id),
    CONSTRAINT pk_notificaciones PRIMARY KEY (id)
);

CREATE INDEX idx_notif_estado ON NOTIFICACIONES(estado);
CREATE INDEX idx_notif_reintento ON NOTIFICACIONES(proximo_reintento);
CREATE INDEX idx_notif_expediente ON NOTIFICACIONES(expediente_id);
CREATE INDEX idx_notif_documento ON NOTIFICACIONES(documento_id);

COMMIT;