ALTER TABLE EXPEDIENTES ADD fase VARCHAR2(100);

UPDATE EXPEDIENTES
SET fase = 'REVISION_ADMINISTRATIVA'
WHERE fase IS NULL;

ALTER TABLE EXPEDIENTES MODIFY fase VARCHAR2(100) NOT NULL;

CREATE INDEX idx_exp_fase ON EXPEDIENTES(fase);